<a href="https://colab.research.google.com/github/DereAbdulhameed/Computer-Vision-Projects/blob/main/TensorFlow_Tensors_and_Basics.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import tensorflow as tf

In [2]:
# creating a zero-dimensional array
tensor_zero_d = tf.constant(6)
print(tensor_zero_d)

tf.Tensor(6, shape=(), dtype=int32)


In [3]:
# creating a Tensor 1-D
tensor_one_d = tf.constant([5, -4, 1])
print(tensor_one_d)

tf.Tensor([ 5 -4  1], shape=(3,), dtype=int32)


In [4]:
# creating a 2-D tensor
tensor_two_d = tf.constant([
    [2,-4,1],
    [3,9,0],
    [7,-4,2]
])
print(tensor_two_d)

tf.Tensor(
[[ 2 -4  1]
 [ 3  9  0]
 [ 7 -4  2]], shape=(3, 3), dtype=int32)


In [5]:
# creating a three_d constant
tensor_three_d = tf.constant([

[[1,2,3],
 [2,3,4]],

 [[2,5,6],
  [6,7,8]],

  [[-3,-1,-8],
   [1,5,9]]
])

print(tensor_three_d)

tf.Tensor(
[[[ 1  2  3]
  [ 2  3  4]]

 [[ 2  5  6]
  [ 6  7  8]]

 [[-3 -1 -8]
  [ 1  5  9]]], shape=(3, 2, 3), dtype=int32)


In [6]:
eye_tensor = tf.eye(
    num_rows = 3,
    num_columns = None,
    batch_shape = None,
    dtype = tf.dtypes.float32,
    name = None
)

print(eye_tensor)

tf.Tensor(
[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]], shape=(3, 3), dtype=float32)


In [7]:
print(3 * eye_tensor)

tf.Tensor(
[[3. 0. 0.]
 [0. 3. 0.]
 [0. 0. 3.]], shape=(3, 3), dtype=float32)


In [8]:
# the eye method
eye_tensor = tf.eye(
    num_rows = 3,
    num_columns = 5,
    batch_shape = [3],
    dtype = tf.dtypes.float32,
    name = None
)

print(eye_tensor)

tf.Tensor(
[[[1. 0. 0. 0. 0.]
  [0. 1. 0. 0. 0.]
  [0. 0. 1. 0. 0.]]

 [[1. 0. 0. 0. 0.]
  [0. 1. 0. 0. 0.]
  [0. 0. 1. 0. 0.]]

 [[1. 0. 0. 0. 0.]
  [0. 1. 0. 0. 0.]
  [0. 0. 1. 0. 0.]]], shape=(3, 3, 5), dtype=float32)


In [9]:
#  the fill method
fill_tensor = tf.fill([2,4],8)

print(fill_tensor)

tf.Tensor(
[[8 8 8 8]
 [8 8 8 8]], shape=(2, 4), dtype=int32)


In [10]:
# the ones_like method
ones_like_tensor = tf.ones_like(fill_tensor)
print(ones_like_tensor)

tf.Tensor(
[[1 1 1 1]
 [1 1 1 1]], shape=(2, 4), dtype=int32)


### INDEXING


In [11]:
indexed_tensor = tf.constant([2,5,7,8,4])
print(indexed_tensor)

tf.Tensor([2 5 7 8 4], shape=(5,), dtype=int32)


In [12]:
#To index the first 4 elements
print(indexed_tensor[0:4])

tf.Tensor([2 5 7 8], shape=(4,), dtype=int32)


In [13]:
# indexing a 2-D tensor
tensor_two_d = tf.constant([
    [2,-4,1],
    [-3,9,0],
    [7,-4,2],
    [4,6,-8]
])
print(tensor_two_d[0:3,:])
print(tensor_two_d[2,:])
print(tensor_two_d[3,-1])

tf.Tensor(
[[ 2 -4  1]
 [-3  9  0]
 [ 7 -4  2]], shape=(3, 3), dtype=int32)
tf.Tensor([ 7 -4  2], shape=(3,), dtype=int32)
tf.Tensor(-8, shape=(), dtype=int32)


In [14]:
# indexing a three_d constant
tensor_three_d = tf.constant([

   [[1,2,3],
   [2,3,4]],

   [[2,5,6],
   [6,7,8]],

   [[-3,-1,-8],
   [1,5,9]]
])

print(tensor_three_d)
print(tensor_three_d[1 , 0 , : ])
print(tensor_three_d[0:2, :, 1])

tf.Tensor(
[[[ 1  2  3]
  [ 2  3  4]]

 [[ 2  5  6]
  [ 6  7  8]]

 [[-3 -1 -8]
  [ 1  5  9]]], shape=(3, 2, 3), dtype=int32)
tf.Tensor([2 5 6], shape=(3,), dtype=int32)
tf.Tensor(
[[2 3]
 [5 7]], shape=(2, 2), dtype=int32)


Maths Function

In [15]:
''' 1. Absolute Function
    2. Add Function
    3. Multiply



'''

' 1. Absolute Function\n\n\n\n\n'

In [20]:
#Absolute Function
x_abs = tf.constant([-2.5,-3.4,2.0])
print(x_abs)
tf.abs(x_abs)

tf.Tensor([-2.5 -3.4  2. ], shape=(3,), dtype=float32)


<tf.Tensor: shape=(3,), dtype=float32, numpy=array([2.5, 3.4, 2. ], dtype=float32)>

In [22]:
x_abs_complex = tf.constant([-2.25 + 4.75j])
tf.abs(x_abs_complex)

<tf.Tensor: shape=(1,), dtype=float64, numpy=array([5.25594901])>

In [24]:
tf.sqrt([(-2.25) ** 2+ 4.75 ** 2])

<tf.Tensor: shape=(1,), dtype=float32, numpy=array([5.255949], dtype=float32)>

In [30]:
#tf.math.divide_no_nan
x_1 = tf.constant([5,3,6,6,4,6], dtype = tf.float32)
x_2 = tf.constant([7,6,2,6,0,11], dtype = tf.float32)

print(tf.add(x_1, x_2))
print(tf.multiply(x_1, x_2))
print(tf.divide(x_1, x_2)) # this will print out infinity at the 5th column, hence the divide_no_nan function
print(tf.math.divide_no_nan(x_1, x_2))

tf.Tensor([12.  9.  8. 12.  4. 17.], shape=(6,), dtype=float32)
tf.Tensor([35. 18. 12. 36.  0. 66.], shape=(6,), dtype=float32)
tf.Tensor([0.71428573 0.5        3.         1.                inf 0.54545456], shape=(6,), dtype=float32)
tf.Tensor([0.71428573 0.5        3.         1.         0.         0.54545456], shape=(6,), dtype=float32)


RAGGED TENSOR: This sort of tensor allows the creating of matrices with different/unequal columns. i.e. a non-rectangular method

In [33]:
tensor_two_d = [[1,2,0],
                [3,],
                [3,5,6,2,1],
                [2,3]]
tensor_ragged = tf.ragged.constant(tensor_two_d)
print(tensor_ragged.shape)
print(tensor_ragged)


(4, None)
<tf.RaggedTensor [[1, 2, 0], [3], [3, 5, 6, 2, 1], [2, 3]]>


In [34]:
print(tf.RaggedTensor.from_row_splits(
      values=[3, 1, 4, 1, 5, 9, 2, 6],
      row_splits=[0, 4, 4, 7, 8, 8]))


<tf.RaggedTensor [[3, 1, 4, 1], [], [5, 9, 2], [6], []]>


SPARSE TENSORS: This allows working with multiple zeros in the tensor

In [37]:
# Sparse tensors store values by index in a memory-efficient manner
sparse_tensor = tf.sparse.SparseTensor(indices=[[0, 0], [1, 2]],
                                       values=[1, 2],
                                       dense_shape=[3, 4])
print(sparse_tensor, "\n")

# You can convert sparse tensors to dense
print(tf.sparse.to_dense(sparse_tensor))

SparseTensor(indices=tf.Tensor(
[[0 0]
 [1 2]], shape=(2, 2), dtype=int64), values=tf.Tensor([1 2], shape=(2,), dtype=int32), dense_shape=tf.Tensor([3 4], shape=(2,), dtype=int64)) 

tf.Tensor(
[[1 0 0 0]
 [0 0 2 0]
 [0 0 0 0]], shape=(3, 4), dtype=int32)


STRING TENSORS

In [38]:
# Tensors can be strings, too here is a scalar string.
scalar_string_tensor = tf.constant("Gray wolf")
print(scalar_string_tensor)

tf.Tensor(b'Gray wolf', shape=(), dtype=string)


In [39]:
# If you have three string tensors of different lengths, this is OK.
tensor_of_strings = tf.constant(["Gray wolf",
                                 "Quick brown fox",
                                 "Lazy dog"])
# Note that the shape is (3,). The string length is not included.
print(tensor_of_strings)

tf.Tensor([b'Gray wolf' b'Quick brown fox' b'Lazy dog'], shape=(3,), dtype=string)
